<?php

namespace Database\Seeders;

use App\Models\OrientationEtablissement;
use Illuminate\Database\Seeder;

/**
 * Le répertoire national : où l'on va après la 3ème et après la terminale.
 *
 * Lycées, universités et grandes écoles du Gabon — ceux vers lesquels un
 * conseiller oriente réellement. Sans ce répertoire, l'élève aurait une
 * recommandation de filière et nulle part où la poser ; l'établissement, lui,
 * n'aurait aucune liste à proposer et chacun retomberait sur la rumeur.
 *
 * Ces entrées n'appartiennent à aucune école (`school_id` nul) : elles valent
 * pour toute la plateforme. Un établissement qui connaît un centre de
 * formation de sa ville l'ajoute depuis son propre écran, et l'ajout ne
 * regarde que lui.
 *
 * Les capacités et les effectifs sont ceux déclarés : ils se mettent à jour
 * depuis l'écran du répertoire, et servent à dire à l'élève si l'établissement
 * a encore de la place.
 */
class RepertoireOrientationSeeder extends Seeder
{
    public function run(): void
    {
        $nouveaux = 0;

        foreach (self::ETABLISSEMENTS as $etablissement) {
            /*
             * `firstOrCreate` sur le nom : le répertoire se re-sème à chaque
             * déploiement, et les capacités mises à jour par un établissement
             * ne doivent pas être écrasées par les valeurs d'origine.
             */
            $existant = OrientationEtablissement::whereNull('school_id')
                ->where('nom', $etablissement['nom'])
                ->first();

            if ($existant) {
                continue;
            }

            OrientationEtablissement::create($etablissement + ['school_id' => null, 'is_active' => true]);
            $nouveaux++;
        }

        $this->command?->info($nouveaux
            ? $nouveaux.' établissement(s) ajouté(s) au répertoire d’orientation.'
            : 'Répertoire d’orientation déjà complet.');
    }

    /**
     * @var array<int, array<string, mixed>>
     */
    private const ETABLISSEMENTS = [
        [
            'nom' => 'Complexe Scolaire Jean-Hilaire Aubame Eyeghe',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Nzeng-Ayong',
            'latitude' => 0.454,
            'longitude' => 9.484,
            'capacite' => 400,
            'inscrits' => 350,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Général', 'Technique'],
        ],
        [
            'nom' => 'Lycée Blaise Pascal',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Charbonnages',
            'latitude' => 0.42,
            'longitude' => 9.455,
            'capacite' => 200,
            'inscrits' => 195,
            'age_min' => 14,
            'age_max' => 17,
            'filieres' => ['Système Français', 'Général'],
        ],
        [
            'nom' => 'Lycée Djoue Dabany',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Awendjé',
            'latitude' => 0.385,
            'longitude' => 9.47,
            'capacite' => 350,
            'inscrits' => 300,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Général'],
        ],
        [
            'nom' => 'Lycée Joseph Ambouroue Avaro',
            'type' => 'lycee',
            'ville' => 'Port-Gentil',
            'quartier' => 'Centre',
            'latitude' => -0.718,
            'longitude' => 8.782,
            'capacite' => 300,
            'inscrits' => 250,
            'age_min' => 14,
            'age_max' => 18,
            'filieres' => ['Général', 'Technique'],
        ],
        [
            'nom' => 'Lycée National Léon Mba',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Sainte-Marie',
            'latitude' => 0.4,
            'longitude' => 9.44,
            'capacite' => 500,
            'inscrits' => 480,
            'age_min' => 14,
            'age_max' => 18,
            'filieres' => ['Scientifique (C, D)', 'Littéraire (A1, A2)', 'B'],
        ],
        [
            'nom' => 'Lycée Nelson Mandela',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Sainte-Marie',
            'latitude' => 0.401,
            'longitude' => 9.442,
            'capacite' => 400,
            'inscrits' => 390,
            'age_min' => 14,
            'age_max' => 18,
            'filieres' => ['Scientifique', 'Littéraire'],
        ],
        [
            'nom' => 'Lycée Paul Indjendjet Gondjout',
            'sigle' => 'LPIG',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Montagne Sainte',
            'latitude' => 0.398,
            'longitude' => 9.45,
            'capacite' => 450,
            'inscrits' => 440,
            'age_min' => 14,
            'age_max' => 18,
            'filieres' => ['Scientifique', 'Littéraire'],
        ],
        [
            'nom' => 'Lycée Privé Ambourhouet',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Nzeng-Ayong',
            'latitude' => 0.452,
            'longitude' => 9.482,
            'capacite' => 300,
            'inscrits' => 250,
            'age_min' => 14,
            'age_max' => 18,
            'filieres' => ['Général', 'Scientifique'],
        ],
        [
            'nom' => 'Lycée Privé Le Bambino',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Nzeng-Ayong',
            'latitude' => 0.448,
            'longitude' => 9.478,
            'capacite' => 200,
            'inscrits' => 180,
            'age_min' => 14,
            'age_max' => 18,
            'filieres' => ['Général', 'Littéraire'],
        ],
        [
            'nom' => 'Lycée Provincial d\'Oyem',
            'type' => 'lycee',
            'ville' => 'Oyem',
            'quartier' => 'Centre-ville',
            'latitude' => 1.6,
            'longitude' => 11.583,
            'capacite' => 450,
            'inscrits' => 400,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Scientifique', 'Littéraire', 'Technique'],
        ],
        [
            'nom' => 'Lycée Provincial de Bitam',
            'type' => 'lycee',
            'ville' => 'Bitam',
            'quartier' => 'Centre-ville',
            'latitude' => 2.083,
            'longitude' => 11.5,
            'capacite' => 300,
            'inscrits' => 260,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Général'],
        ],
        [
            'nom' => 'Lycée Provincial de Koulamoutou',
            'type' => 'lycee',
            'ville' => 'Koulamoutou',
            'quartier' => 'Centre-ville',
            'latitude' => -1.133,
            'longitude' => 12.483,
            'capacite' => 350,
            'inscrits' => 300,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Général', 'Technique'],
        ],
        [
            'nom' => 'Lycée Provincial de Lambaréné',
            'type' => 'lycee',
            'ville' => 'Lambaréné',
            'quartier' => 'Centre-ville',
            'latitude' => -0.7,
            'longitude' => 10.233,
            'capacite' => 400,
            'inscrits' => 360,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Général', 'Technique'],
        ],
        [
            'nom' => 'Lycée Provincial de Makokou',
            'type' => 'lycee',
            'ville' => 'Makokou',
            'quartier' => 'Centre-ville',
            'latitude' => 0.567,
            'longitude' => 12.867,
            'capacite' => 350,
            'inscrits' => 300,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Général', 'Technique'],
        ],
        [
            'nom' => 'Lycée Provincial de Moanda',
            'type' => 'lycee',
            'ville' => 'Moanda',
            'quartier' => 'Centre-ville',
            'latitude' => -1.567,
            'longitude' => 13.2,
            'capacite' => 400,
            'inscrits' => 350,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Général', 'Technique'],
        ],
        [
            'nom' => 'Lycée Provincial de Mouila',
            'type' => 'lycee',
            'ville' => 'Mouila',
            'quartier' => 'Centre-ville',
            'latitude' => -1.867,
            'longitude' => 11.056,
            'capacite' => 400,
            'inscrits' => 340,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Général', 'Technique'],
        ],
        [
            'nom' => 'Lycée Provincial de Ntoum',
            'type' => 'lycee',
            'ville' => 'Ntoum',
            'quartier' => 'Centre-ville',
            'latitude' => 0.393,
            'longitude' => 9.767,
            'capacite' => 350,
            'inscrits' => 300,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Général'],
        ],
        [
            'nom' => 'Lycée Provincial de Tchibanga',
            'type' => 'lycee',
            'ville' => 'Tchibanga',
            'quartier' => 'Centre-ville',
            'latitude' => -2.85,
            'longitude' => 11.017,
            'capacite' => 350,
            'inscrits' => 300,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Général', 'Technique'],
        ],
        [
            'nom' => 'Lycée Public de Nzeng-Ayong',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Nzeng-Ayong',
            'latitude' => 0.451,
            'longitude' => 9.481,
            'capacite' => 800,
            'inscrits' => 750,
            'age_min' => 14,
            'age_max' => 19,
            'filieres' => ['Scientifique (C, D)', 'Littéraire (A1, A2)', 'B'],
        ],
        [
            'nom' => 'Lycée Technique Agathe Obendje',
            'type' => 'lycee',
            'ville' => 'Franceville',
            'quartier' => 'Centre',
            'latitude' => -1.632,
            'longitude' => 13.582,
            'capacite' => 250,
            'inscrits' => 200,
            'age_min' => 15,
            'age_max' => 20,
            'filieres' => ['Technique', 'Professionnel'],
        ],
        [
            'nom' => 'Lycée Technique National Omar Bongo',
            'sigle' => 'LTNOB',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Owendo',
            'latitude' => 0.352,
            'longitude' => 9.502,
            'capacite' => 600,
            'inscrits' => 550,
            'age_min' => 15,
            'age_max' => 20,
            'filieres' => ['Industriel', 'Génie Civil', 'Mécanique', 'Électronique'],
        ],
        [
            'nom' => 'Lycée d\'Etat de l\'Estuaire',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Owendo',
            'latitude' => 0.35,
            'longitude' => 9.5,
            'capacite' => 400,
            'inscrits' => 350,
            'age_min' => 15,
            'age_max' => 19,
            'filieres' => ['Technique (F, E)', 'Professionnel'],
        ],
        [
            'nom' => 'Lycée de MBELE',
            'type' => 'lycee',
            'ville' => 'Libreville',
            'quartier' => 'Nzeng-Ayong',
            'latitude' => 0.458,
            'longitude' => 9.488,
            'capacite' => 600,
            'inscrits' => 500,
            'age_min' => 14,
            'age_max' => 20,
            'filieres' => ['Général', 'Technique'],
        ],
        [
            'nom' => 'Université Franco-Gabonaise Saint-Exupéry',
            'type' => 'universite',
            'ville' => 'Libreville',
            'quartier' => 'Batterie IV',
            'latitude' => 0.41,
            'longitude' => 9.43,
            'filieres' => ['Droit', 'Sciences Politiques', 'Gestion', 'Sciences Humaines'],
            'description' => 'Enseignement supérieur privé aux standards internationaux.',
        ],
        [
            'nom' => 'Université Omar Bongo',
            'sigle' => 'UOB',
            'type' => 'universite',
            'ville' => 'Libreville',
            'quartier' => 'Université',
            'latitude' => 0.41,
            'longitude' => 9.46,
            'filieres' => [
                'Droit',
                'Lettres Modernes',
                'Sociologie',
                'Psychologie',
                'Economie',
                'Anthropologie',
                'Géographie',
                'Histoire',
            ],
            'description' => 'La plus ancienne et grande université publique, spécialisée en sciences humaines, droit et économie.',
        ],
        [
            'nom' => 'Université des Sciences de la Santé',
            'sigle' => 'USS',
            'type' => 'universite',
            'ville' => 'Libreville',
            'quartier' => 'Owendo',
            'latitude' => 0.34,
            'longitude' => 9.51,
            'filieres' => ['Médecine', 'Pharmacie', 'Maïeutique', 'Biologie Médicale'],
            'description' => 'Formation des médecins et professionnels de santé du Gabon.',
        ],
        [
            'nom' => 'Université des Sciences et Techniques de Masuku',
            'sigle' => 'USTM',
            'type' => 'universite',
            'ville' => 'Franceville',
            'quartier' => 'Masuku',
            'latitude' => -1.633,
            'longitude' => 13.583,
            'filieres' => ['Biologie', 'Géologie', 'Mathématiques', 'Physique', 'Chimie', 'Ingénierie'],
            'description' => 'Pôle d\'excellence pour les sciences fondamentales et technologiques.',
        ],
        [
            'nom' => 'BGFI Business School',
            'sigle' => 'BBS',
            'type' => 'ecole_superieure',
            'ville' => 'Libreville',
            'quartier' => 'Louis',
            'latitude' => 0.405,
            'longitude' => 9.448,
            'filieres' => ['Banque', 'Finance', 'Assurance', 'Comptabilité Contrôle Audit'],
            'description' => 'L\'école de référence pour les métiers de la banque et de la finance.',
        ],
        [
            'nom' => 'Ecole Nationale des Eaux et Forêts',
            'sigle' => 'ENEF',
            'type' => 'ecole_superieure',
            'ville' => 'Cap Estérias',
            'quartier' => 'Cap Estérias',
            'latitude' => 0.616,
            'longitude' => 9.333,
            'filieres' => ['Foresterie', 'Environnement', 'Pêche', 'Aquaculture'],
            'description' => 'Cadres pour la gestion des ressources naturelles et de l\'environnement.',
        ],
        [
            'nom' => 'Ecole Normale Supérieure',
            'sigle' => 'ENS',
            'type' => 'ecole_superieure',
            'ville' => 'Libreville',
            'quartier' => 'Zone ENS',
            'latitude' => 0.415,
            'longitude' => 9.465,
            'filieres' => ['Enseignement Secondaire', 'Sciences de l\'Education'],
            'description' => 'Formation des professeurs de collèges et lycées.',
        ],
        [
            'nom' => 'Ecole Normale Supérieure de l\'Enseignement Technique',
            'sigle' => 'ENSET',
            'type' => 'ecole_superieure',
            'ville' => 'Libreville',
            'quartier' => 'Sainte-Marie',
            'latitude' => 0.402,
            'longitude' => 9.443,
            'filieres' => ['Génie Civil', 'Génie Mécanique', 'Génie Electrique', 'Techniques Administratives'],
            'description' => 'Formation des enseignants techniques et ingénieurs technologues.',
        ],
        [
            'nom' => 'Institut Africain d\'Informatique',
            'sigle' => 'IAI',
            'type' => 'ecole_superieure',
            'ville' => 'Libreville',
            'quartier' => 'Centre-ville',
            'latitude' => 0.39,
            'longitude' => 9.455,
            'filieres' => ['Informatique de Gestion', 'Systèmes et Réseaux', 'Génie Logiciel'],
            'description' => 'Ecole inter-états spécialisée dans l\'informatique.',
        ],
        [
            'nom' => 'Institut National des Sciences de Gestion',
            'sigle' => 'INSG',
            'type' => 'ecole_superieure',
            'ville' => 'Libreville',
            'quartier' => 'Gros-Bouquet',
            'latitude' => 0.42,
            'longitude' => 9.45,
            'filieres' => ['Comptabilité', 'Marketing', 'Gestion RH', 'Commerce International', 'Banque'],
            'description' => 'Référence nationale pour les formations en gestion et management.',
        ],
        [
            'nom' => 'Institut Supérieur de Technologie',
            'sigle' => 'IST',
            'type' => 'ecole_superieure',
            'ville' => 'Libreville',
            'quartier' => 'Zone Industrielle Oloumi',
            'latitude' => 0.37,
            'longitude' => 9.46,
            'filieres' => ['Maintenance Industrielle', 'Génie Electrique', 'Structures Métalliques'],
            'description' => 'Formation de techniciens supérieurs opérationnels.',
        ],
        [
            'nom' => 'Institut Universitaire des Sciences de l\'Organisation',
            'sigle' => 'IUSO',
            'type' => 'ecole_superieure',
            'ville' => 'Libreville',
            'quartier' => 'Montagne Sainte',
            'latitude' => 0.399,
            'longitude' => 9.451,
            'filieres' => ['Secrétariat de Direction', 'Gestion Logistique', 'Communication', 'Droit des Affaires'],
            'description' => 'Formation professionnalisante dans les métiers du tertiaire.',
        ],
        [
            'nom' => 'Institut du Pétrole et du Gaz',
            'sigle' => 'IPG',
            'type' => 'ecole_superieure',
            'ville' => 'Port-Gentil',
            'quartier' => 'Zone Industrielle',
            'latitude' => -0.725,
            'longitude' => 8.79,
            'filieres' => ['Ingénierie Pétrolière', 'Logistique Pétrolière', 'QHSE'],
            'description' => 'Formation spécialisée pour l\'industrie pétrolière.',
        ],
        [
            'nom' => 'Sup de Com Gabon',
            'type' => 'ecole_superieure',
            'ville' => 'Libreville',
            'quartier' => 'Glass',
            'latitude' => 0.395,
            'longitude' => 9.445,
            'filieres' => ['Communication', 'Marketing Digital', 'Publicité'],
            'description' => 'Ecole supérieure de communication.',
        ],
    ];
}
